export const unicorns_model = [
    {
        func: 'getUnicorn',
        type: 'get',
        route: '/unicorns/:unicorn_id',
        has_body: false,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'getAllUnicorns',
        type: 'get',
        route: '/unicorns/',
        has_body: false,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'createUnicorn',
        type: 'post',
        route: '/unicorns/',
        has_body: true,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'updateUnicorn',
        type: 'patch',
        route: '/unicorns/:unicorn_id',
        has_body: true,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'deleteUnicorn',
        type: 'delete',
        route: '/unicorns/:unicorn_id',
        has_body: false,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'resetUnicorns',
        type: 'delete',
        route: '/unicorns/',
        has_body: false,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
]