export const users_model = [
    {
        func: 'getUser',
        type: 'get',
        route: '/users/:user_id',
        has_body: false,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'getAllUsers',
        type: 'get',
        route: '/users/',
        has_body: false,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'createUser',
        type: 'post',
        route: '/users/',
        has_body: true,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'updateUser',
        type: 'patch',
        route: '/users/:user_id',
        has_body: true,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'deleteUser',
        type: 'delete',
        route: '/users/:user_id',
        has_body: false,
        has_params: true,
        body_filters: [],
        params_filters: [],
    },
    {
        func: 'resetUser',
        type: 'delete',
        route: '/users/',
        has_body: false,
        has_params: false,
        body_filters: [],
        params_filters: [],
    },
]