export const users_model = [
  {
    func: "getUser",
    type: "get",
    route: "/users/:user_id",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
  {
    func: "getAllUsers",
    type: "get",
    route: "/users/",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
  {
    func: "createUser",
    type: "post",
    route: "/users/",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
  {
    func: "updateUser",
    type: "patch",
    route: "/users/:user_id",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
  {
    func: "deleteUser",
    type: "delete",
    route: "/users/:user_id",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
  {
    func: "resetUser",
    type: "delete",
    route: "/users/",
    exclude_body: [],
    exclude_params: [],
    middlewares: [],
  },
];